name: quantecon
channels:
  - default
dependencies:
  - python=3.9
  - anaconda=2022.05
  - pip
  - pip:
    - jupyter-book==0.13.1
    - quantecon-book-theme==0.3.1
    - sphinx-tojupyter==0.2.1
    - sphinxext-rediraffe==0.2.7
    - sphinx-exercise==0.4.0
    - ghp-import==2.1.0
    - sphinxcontrib-youtube==1.2.0
    - sphinx-togglebutton==0.3.2
    # Sandpit Requirements
    - quantecon
    - array-to-latex
    - PuLP
    - cvxpy
    - cvxopt
    - cylp
    - prettytable
